### ISSUE TITLE
rename Global ID lookup service

### ISSUE THREAD

**Issue by kurzum** [dbpedia/dev.dbpedia.org#3]
lookup already exists
we should name it Global IRI Resolution Service

**Comment by kurzum** [comment]
or Global Same Same Service or Same Thing Service

**Comment by kurzum** [comment]
SameSame is actually my preference

**Comment by Vehnem** [comment]
Selected Global IRI Resolution Service. You can change it in readme-list.tsv for the outline and in the README.md of the project for the h1 on the page.

**Comment by aolieman** [comment]
> SameSame is actually my preference

I like this name as well. There are some other projects on GitHub with this name, but I don't see that as a problem. Are we going to make the change, also renaming the SameSame repo?
