### ISSUE TITLE
problem with rendering first markdown heading

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/dev.dbpedia.org#8]
see http://dev.dbpedia.org/DBpedia%20Live%20Mirroring

**Comment by Vehnem** [comment]
Not fixable for me.
Markdown library bug in jekyll.
* pls use hashtag syntax for heading
* or change ========== to =========

**Comment by Vehnem** [comment]
fixed

**Comment by JJ-Author** [comment]
confirmed
